// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjvcznltzejgdfdzuwci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqdmN6bmx0emVqZ2RmZHp1d2NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNzU5ODUsImV4cCI6MjA2Mjk1MTk4NX0.N1SFKl-twmb43gNIHRV9B-x3dtuvBCTtkCr_SW3Cppw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);